"""add_access_requests_table

Revision ID: 08b97ac7637a
Revises: a5f2da8dd820
Create Date: 2026-08-06 17:12:38.858783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08b97ac7637a'
down_revision: Union[str, Sequence[str], None] = 'a5f2da8dd820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_requests', sa.Column('message', sa.String(length=500), nullable=True))
    op.add_column('access_requests', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('access_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='requeststatusenum'),
               nullable=False)
    op.alter_column('access_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('access_requests_person_id_fkey'), 'access_requests', type_='foreignkey')
    op.drop_constraint(op.f('access_requests_requester_id_fkey'), 'access_requests', type_='foreignkey')
    op.drop_constraint(op.f('access_requests_tree_id_fkey'), 'access_requests', type_='foreignkey')
    op.create_foreign_key(None, 'access_requests', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'access_requests', 'trees', ['tree_id'], ['id'], ondelete='CASCADE')
    op.drop_column('access_requests', 'person_id')
    op.alter_column('life_events', 'date_approx',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('life_events', 'source',
               existing_type=postgresql.ENUM('AUTO', 'MANUAL', name='eventsourceenum'),
               nullable=False)
    op.alter_column('life_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('life_events_person_id_fkey'), 'life_events', type_='foreignkey')
    op.create_foreign_key(None, 'life_events', 'persons', ['person_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'life_events', type_='foreignkey')
    op.create_foreign_key(op.f('life_events_person_id_fkey'), 'life_events', 'persons', ['person_id'], ['id'])
    op.alter_column('life_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('life_events', 'source',
               existing_type=postgresql.ENUM('AUTO', 'MANUAL', name='eventsourceenum'),
               nullable=True)
    op.alter_column('life_events', 'date_approx',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('access_requests', sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'access_requests', type_='foreignkey')
    op.drop_constraint(None, 'access_requests', type_='foreignkey')
    op.create_foreign_key(op.f('access_requests_tree_id_fkey'), 'access_requests', 'trees', ['tree_id'], ['id'])
    op.create_foreign_key(op.f('access_requests_requester_id_fkey'), 'access_requests', 'users', ['requester_id'], ['id'])
    op.create_foreign_key(op.f('access_requests_person_id_fkey'), 'access_requests', 'persons', ['person_id'], ['id'])
    op.alter_column('access_requests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('access_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='requeststatusenum'),
               nullable=True)
    op.drop_column('access_requests', 'updated_at')
    op.drop_column('access_requests', 'message')
    # ### end Alembic commands ###
