"""add collaboration tables: tree_collaborators, tree_invites, change_requests

Revision ID: 7b1152b290da
Revises: ee5a4206cdda
Create Date: 2026-09-18 17:03:59.023784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b1152b290da'
down_revision: Union[str, Sequence[str], None] = 'ee5a4206cdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'CO_EDITOR', 'EDITOR', 'VIEWER', name='collaboratorroleenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='invitestatusenum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_invites_id'), 'tree_invites', ['id'], unique=False)
    op.create_index(op.f('ix_tree_invites_tree_id'), 'tree_invites', ['tree_id'], unique=False)
    op.drop_index(op.f('ix_trees_id'), table_name='trees')
    op.drop_table('trees')
    op.add_column('change_requests', sa.Column('current_data', sa.JSON(), nullable=True))
    op.add_column('change_requests', sa.Column('auto_approved_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_change_requests_owner_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_requested_by_id'), table_name='change_requests')
    op.add_column('tree_collaborators', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_tree_collaborators_user_id'), table_name='tree_collaborators')
    op.drop_constraint(op.f('tree_collaborators_tree_id_fkey'), 'tree_collaborators', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('tree_collaborators_tree_id_fkey'), 'tree_collaborators', 'trees', ['tree_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tree_collaborators_user_id'), 'tree_collaborators', ['user_id'], unique=False)
    op.drop_column('tree_collaborators', 'updated_at')
    op.create_index(op.f('ix_change_requests_requested_by_id'), 'change_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_change_requests_owner_id'), 'change_requests', ['owner_id'], unique=False)
    op.drop_column('change_requests', 'auto_approved_at')
    op.drop_column('change_requests', 'current_data')
    op.create_table('trees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trees_pkey'))
    )
    op.create_index(op.f('ix_trees_id'), 'trees', ['id'], unique=False)
    op.drop_index(op.f('ix_tree_invites_tree_id'), table_name='tree_invites')
    op.drop_index(op.f('ix_tree_invites_id'), table_name='tree_invites')
    op.drop_table('tree_invites')
    # ### end Alembic commands ###
