"""add_pg_trgm_extension_and_indexes

Revision ID: a5f2da8dd820
Revises: c7bf51ec755a
Create Date: 2026-08-05 17:38:10.153848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f2da8dd820'
down_revision: Union[str, Sequence[str], None] = 'c7bf51ec755a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
