"""add_access_requests_table

Revision ID: eba0f3eeb2c8
Revises: 08b97ac7637a
Create Date: 2026-08-06 17:31:36.096165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba0f3eeb2c8'
down_revision: Union[str, Sequence[str], None] = '08b97ac7637a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
